version: '3.8'

services:
  # C++ Engine Builder (run separately)
  engine-builder:
    build:
      context: .
      dockerfile: docker/Dockerfile.engine
    image: mmg-engine:latest
    profiles:
      - build

  # Python Gateway (FastAPI + WebSocket)
  gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.gateway
    image: mmg-gateway:latest
    container_name: mmg-gateway
    restart: unless-stopped
    volumes:
      - ./exports:/app/exports
      # For development, mount source code
      # - ./gateway/app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mmg-network

  # Nginx (serves Flutter + proxies WebSocket)
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    image: mmg-nginx:latest
    container_name: mmg-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gateway
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - mmg-network
    # For SSL certificates (Let's Encrypt)
    # volumes:
    #   - ./certs:/etc/nginx/certs:ro
    #   - ./ssl-conf:/etc/nginx/ssl:ro

networks:
  mmg-network:
    driver: bridge

volumes:
  exports:
    driver: local

