name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake python3 python3-dev python3-pip
        pip3 install pybind11
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    
    - name: Build all
      run: |
        chmod +x scripts/build_all.sh
        ./scripts/build_all.sh
    
    - name: Get version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Create release tarball
      run: |
        cd build
        mv mmg_*.tar.gz mmg_${{ steps.version.outputs.VERSION }}.tar.gz
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/mmg_${{ steps.version.outputs.VERSION }}.tar.gz
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker images
      if: github.repository == 'owner/themarketmakinggame'
      run: |
        echo "Docker push would happen here with proper credentials"
        # docker login
        # docker build and push images with version tags

